### PR TITLE
More links with imageboards and textboards

### PR DESCRIPTION
**Pull request by mithlardman**
just more links

### CODE REVIEW

**Comment by ccd0** [comment]
Thanks.

**Comment by mithlardman** [comment]
> Thanks.

you're welcome :D

Btw you could add this other link if you want it! https://allthetropes.org/wiki/Image_Boards

**Comment by ccd0** [comment]
Done. 6e468c3b7ab32bca4934f7fbd012ad808cac0c81

**Comment by mithlardman** [comment]
if you wish you can put this pastebin of the 2016 version of creamy list https://pastebin.com/3e2RddP5

**Comment by ccd0** [comment]
8a7101c5e28f12939bc9266f50c9d53f012e7d51

**Comment by mithlardman** [comment]
hey i found this link https://4taba.net/res/brd/f/37/1520113924746/main.html if you paste it in the wayback machine it will redirect you to a random imageboard, you can use it and add it to the list to found more imageboards if you want it!

**Pull request merged**
